version: "3.8"

services:
  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/music?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ASD123
      MINIO_DATASOURCE_URL: minio
      MINIO_ROOT_USER: minio99
      MINIO_ROOT_PASSWORD: minio123
      GRPC_RECOMMENDATION_SERVER_PORT: 9090
      GRPC_RECOMMENDATION_SERVER_HOST: recommendation-engine
    depends_on:
      - minio
      - mysql-db
  recommendation-engine:
    build:
      context: ./backend-recommendation-engine
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/music?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ASD123
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ASD123"
      MYSQL_DATABASE: "music"
      restart: always
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio99
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    restart: always

volumes:
  mysql-volume:
  minio-data: