apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-upload-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-upload-redis
  template:
    metadata:
      labels:
        app: music-upload-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
---
apiVersion: v1
kind: Service
metadata:
  name: music-upload-redis-service
spec:
  selector:
    app: music-upload-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP